apps/accounts/urls.py
from django.urls import path
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView, \
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('change-password/', views.change_password,
         name='change_password'),
    path('reset-password/',
         PasswordResetView.as_view(template_name='accounts/reset_password.html'
         , success_url=reverse_lazy('accounts:password_reset_done'),
         email_template_name='accounts/email_template.html'),
         name='password_reset'),
    path('reset-password/done/',
         PasswordResetDoneView.as_view(template_name='accounts/reset_password_done.html'
         ), name='password_reset_done'),
    path('reset-password/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(success_url=reverse_lazy('accounts:password_reset_complete'
         )), name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='accounts/reset_password_complete.html'),
         name='password_reset_complete'),
    ]

apps/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [path('', views.home, name='home')]

apps/upload/urls.py
from django.urls import path
from . import views

app_name = "upload"

urlpatterns = [
    path('', views.UploadView.as_view(), name='drag_and_drop'),
    path('<int:id>/delete/', views.FileDelete.as_view(), name='file-delete'),
    path('<str:csv_name>/graph/', views.GraphView.as_view(), name='graph'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls')),
    path('account/', include('apps.accounts.urls')),
    path('projectavalon/', include('apps.upload.urls')),
    path('tensor/', include('apps.tensor.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/html/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Algoraise: Project Avalon{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'base/css/vendor/bootstrap/bootstrap.min.css' %}">

    <!-- AOS (Animate on Scroll) -->
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">

    <!-- CUSTOM CSS -->
    <link rel="stylesheet" href="{% static 'base/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/form.css' %}">
    {% block css %}
    {% endblock %}
</head>

<body>
    <div class="main-wrapper">

        <!-- NAVIGATION -->
        <nav id="main-menu" class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'main:home' %}">Project Avalon</a>

                <!-- Burger menu -->
                <button class="navbar-toggler nav-button" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <div class="menu-icon"><span></span><span></span><span></span><span></span></div>
                </button>

                <!-- On-page navigation -->
                <div class="collapse navbar-collapse" id="navbarResponsive" style="height:40px;">
                    <ul class="navbar-nav ml-auto">
                        <div class="dropdown-divider"></div>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'upload:drag_and_drop' %}">Project Avalon</a>
                        </li>

                        <!-- Login/logout buttons -->
                        <li class="nav-item dropdown">
                            {% if user.is_authenticated %}
                            <a class="nav-link dropdown-toggle" href="#" id="profile-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                {{ user.username }}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item nav-link" href="{% url 'accounts:view_profile' %}">View profile</a>
                                <a class="dropdown-item nav-link" href="{% url 'accounts:edit_profile' %}">Edit profile</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item nav-link" href="{% url 'accounts:logout' %}">Log out</a>
                            </div>
                            {% else %}
                            <a class="nav-link" href="{% url 'accounts:login' %}">Log in</a>
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </div>
        </nav>


        <!-- CONTENTS -->
        <div id="base-wrapper" class="d-flex flex-grow-1 flex-column">
            {% block content %}
            {% endblock %}
        </div>

        <!-- FOOTER -->
        <footer class="bg-dark">
            <div class="container">
                <div class="footer-links">
                    <a class="btn-standard" href="https://algoraise.com/" target="_blank">Algoraise</a>
                    <a class="btn-standard" href="http://students.cs.ucl.ac.uk/2018/group29/index.html" target="_blank">Project</a>
                    <a class="btn-standard" href="https://www.ucl.ac.uk/" target="_blank">UCL</a>
                </div>
                <p class="m-0 text-center text-white">Copyright &copy; Team 29 2019.</p>
            </div>
        </footer>

    </div>

    <!-- VENDOR -->
    <script src="{% static 'base/js/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'base/js/vendor/bootstrap/bootstrap.bundle.min.js' %}"></script>

    <!-- AOS -->
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>
      AOS.init()
    </script>

    <!-- NAVBAR -->
    <script src="{% static 'base/js/nav-icon.js' %}"></script>
    <script src="{% static 'base/js/csrf.js' %}"></script>

    <!-- ADDITIONAL SCRIPTS -->
    {% block javascript %}
    {% endblock %}
</body>

</html>

templates/base/html/documentation.html
{% extends "base/html/base.html" %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'base/css/documentation.css' %}">
<!-- ADDITIONAL CSS -->
{% block upload-css %}{% endblock %}
{% endblock %}

{% block content %}

<!-- UPLOAD APP GOES HERE -->
{% block upload-html %}{% endblock %}

<div class="container my-20 px-0" data-aos="fade-up">
  <!-- DOCUMENTATION -->
  <section id="documentation" class="page-section">
    <div class="container h-100">
      <form method="get" action="{% static 'downloads/user-manual.pdf' %}">
        <button class="btn-standard black-style" type="submit">Download user manual</button>
      </form>
    </div>
  </section>
</div>
{% endblock %}