apps/accounts/urls.py
from django.urls import path
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView, \
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('change-password/', views.change_password,
         name='change_password'),
    path('reset-password/',
         PasswordResetView.as_view(template_name='accounts/reset_password.html'
         , success_url=reverse_lazy('accounts:password_reset_done'),
         email_template_name='accounts/email_template.html'),
         name='password_reset'),
    path('reset-password/done/',
         PasswordResetDoneView.as_view(template_name='accounts/reset_password_done.html'
         ), name='password_reset_done'),
    path('reset-password/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(success_url=reverse_lazy('accounts:password_reset_complete'
         )), name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='accounts/reset_password_complete.html'),
         name='password_reset_complete'),
    ]

apps/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [path('', views.home, name='home')]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.main.urls')),
    path('account/', include('apps.accounts.urls')),
    path('projectavalon/', include('apps.upload.urls')),
    path('tensor/', include('apps.tensor.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class UserProfile(models.Model):

    """ Creates user profile model. Can be monitored using Django Admin. """

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        """ Returns the username of the user. """

        return self.user.username


def create_profile(
    sender,
    instance,
    created,
    **kwargs
    ):
    """  Creates user and adds to user profile model. """

    if created:
        UserProfile.objects.create(user=instance)


# Saves user profile to database

post_save.connect(create_profile, sender=User)

apps/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserChangeForm


class SignUpForm(forms.Form):

    """ Defines the sign up form fields and input handling.
        NOTE: Cleaning the input fields removes potential code input from
        the user. """

    username = forms.CharField(label='Username', min_length=4,
                               max_length=150)
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(label='Password',
                                widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password',
                                widget=forms.PasswordInput)
    regkey = forms.CharField(label='Registration key')

    class Meta:

        """ Specifies the fields related to the form. """

        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
            )

    def clean_username(self):
        """ Cleans and checks username does not already exist. """

        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise ValidationError('Username already exists.')
        return username

    def clean_email(self):
        """ Cleans email and checks email does not already exist. """

        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise ValidationError('Email already exists.')
        return email

    def clean_password2(self):
        """ Cleans and checks password match. """

        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords don't match.")

        return password2

    def clean_regkey(self):
        """ Clean register key and checks that it matches the secret key. """

        regkey = self.cleaned_data.get('regkey')
        if regkey != '1a4bCddeJk9mt':
            raise ValidationError('Incorrect registration key.')
        return regkey

    def save(self, commit=True):
        """ Creates user if field inputs are all valid. """

        user = User.objects.create_user(self.cleaned_data['username'],
                self.cleaned_data['email'],
                self.cleaned_data['password1'])
        return user


class EditProfileForm(UserChangeForm):

    """ Form for user to edit their profile. """

    class Meta:

        """ Specifies the fields the user can edit. """

        model = User
        fields = ('email', 'first_name', 'last_name', 'password')

apps/accounts/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.urls import reverse  # allows mapping of URLS to app names
from django.views import generic
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import LoginView
from .forms import EditProfileForm, SignUpForm


class Login(LoginView):

    """ Inherits from Django's built-in LoginView, handling GET/POST requests
        on the login page. """

    template_name = 'accounts/login.html'

    def get(
        self,
        request,
        *args,
        **kwargs
        ):
        """ If the user is already logged in: redirect to the home page.
            Else: load the login page. """

        if self.request.user.is_authenticated:
            messages.warning(request, 'You are already logged in.')
            return redirect(reverse('main:home'))
        return super(Login, self).get(request, *args, **kwargs)


class SignUp(generic.CreateView):

    """ Inherits from Django's built-in CreateView, to create a sign up form.
        Handles GET/POST requests for the page. """

    form_class = SignUpForm
    template_name = 'accounts/signup.html'

    def get(self, request):
        """ Load the appropriate page for the user. """

        if self.request.user.is_authenticated:
            messages.warning(request, 'You are already logged in.')
            return redirect(reverse('main:home'))
        form = self.form_class(None)

        # Send an empty form to the user to fill in

        return render(request, self.template_name, {'form': form})

    def post(self, request):
        """ Validate the form and provide feedback. """

        form = self.form_class(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'Account created successfully.')
            return redirect('accounts:login')

        messages.warning(request,
                         'Invalid form entry. Please correct the highlighted fields.'
                         )
        return render(request, self.template_name, {'form': form})  # invalid entry


def view_profile(request):
    """ Simple view for handling the view profile page. """

    if request.method == 'GET':
        if not request.user.is_authenticated:
            messages.warning(request,
                             'You must log in before you can access your profile.'
                             )
            return redirect(reverse('accounts:login'))
    args = {'user': request.user}

    # Send the user's details to display if logged in

    return render(request, 'accounts/profile.html', args)


def edit_profile(request):
    """ Simple view for handling the edit profile page. """

    if request.method == 'POST':

        # Get specific user's inputted form

        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:view_profile'))
    else:
        if not request.user.is_authenticated:
            messages.warning(request,
                             'You must log in before you can edit your profile.'
                             )
            return redirect(reverse('accounts:login'))
        form = EditProfileForm(instance=request.user)
        args = {'form': form}

        # Send an empty form for the user to edit their details

        return render(request, 'accounts/edit_profile.html', args)


def change_password(request):
    """ Simple view for handling the change password page. """

    if request.method == 'POST':

        # Get specific user's inputted form

        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse('accounts:view_profile'))
        else:
            return redirect(reverse('accounts:change_password'))
    else:
        if not request.user.is_authenticated:
            messages.warning(request,
                             'You must log in before you can change your password.'
                             )
            return redirect(reverse('accounts:login'))
        form = PasswordChangeForm(user=request.user)

        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)

apps/accounts/templates/accounts/change_password.html
{% extends "base/html/base.html" %}

{% load static %}

{% block title %}Change password - Project Avalon{% endblock %}

{% block css %}
<!-- CUSTOM PAGE STYLES -->
<link rel="stylesheet" href="{% static 'accounts/css/style.css' %}">
{% endblock %}

{% block content %}
<!-- CHANGE PASSWORD SECTION -->
<div class="container my-20" data-aos="fade-up">
    <h1 class="mb-20">Change password</h1>
    <!-- FORM -->
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" id="submit-profile" class="btn-standard content-btn success mb-20 mt-20">Submit</button>
    </form>
</div>
{% endblock %}

apps/accounts/templates/accounts/edit_profile.html
{% extends "base/html/base.html" %}

{% load static %}

{% block title %}Edit profile - Project Avalon{% endblock %}

{% block css %}
<!-- CUSTOM PAGE STYLES -->
<link rel="stylesheet" href="{% static 'accounts/css/style.css' %}">
{% endblock %}

{% block content %}
<!-- EDIT PROFILE SECTION -->
<div class="container my-20" data-aos="fade-up">
    <h1 class="mb-20">Edit profile</h1>
    <!-- FORM -->
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <a class="link-btn" href="{% url 'accounts:change_password' %}">Change password here.</a>
        <button type="submit" id="submit-profile" class="btn-standard content-btn success mb-20 mt-20">Submit</button>
    </form>
</div>
{% endblock %}


{% block javascript %}
<script>
    // Remove unwanted form outputs
    $(document).ready(function() {
        $("#id_password, .helptext, label[for='id_password']").remove();
    });
</script>
{% endblock %}

apps/accounts/templates/accounts/email_template.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The Project Avalon team{% endblocktrans %}

{% endautoescape %}

apps/accounts/templates/accounts/login.html
{% extends "base/html/base.html" %}

{% load static %}

{% block title %}Log in - Project Avalon{% endblock %}

{% block content %}

<!-- FORM ERROR MESSAGES -->
{% if form.non_field_errors %}
<div class="page-message form-error" style="display:none;" role="alert">
    {% for error in form.non_field_errors %}
    <p class="container">{{ error }}</p>
    {% endfor %}
</div>
{% endif %}

<!-- BACKEND MESSAGES -->
{% if messages %}
<div class="page-message msg" style="display:none;" role="alert">
    {% for message in messages %}
    <p class="container">{{ message }}</p>
    {% endfor %}
</div>
{% endif %}

<!-- LOGIN SECTION -->
<div class="form-page">
    <div class="form fade-in-top">
        <!-- FORM -->
        <form method="post" action="{% url 'accounts:login' %}">
            {% csrf_token %}
            <p><input type="text" name="username" autofocus="" required="" id="id_username" class="input-field" placeholder="username"></p>

            <p><input type="password" name="password" required="" id="id_password" class="input-field" placeholder="password"></p>

            <button type="submit" value="Login">Login</button>
            <a class="form-link" href="{% url 'accounts:signup' %}"">Don't have an account? Sign up</a><br>
            <a class=" form-link" href="{% url 'accounts:password_reset' %}"">Forgot your password? Reset password</a>
        </form>
    </div>
</div>
{% endblock %}


{% block javascript %}
<script src="{% static 'accounts/js/form-error.js' %}"></script>
<script>
    // FORM ERROR HANDLING
    {% if form.non_field_errors %}
    shakeForm();
    showMessage('.form-error');
    {% endif %}

    // BACKEND MESSAGE HANDLING
    {% if messages %}
    {% for message in messages %}
        {% if message.tags == 'warning' %}
        messageType('form-error');
        {% else %}
        messageType('form-complete');
        {% endif %}
        showMessage('.msg');
    {% endfor %}
    {% endif %}
</script>
{% endblock %}

apps/accounts/templates/accounts/profile.html
{% extends "base/html/base.html" %}

{% load static %}

{% block title %}Profile - Project Avalon{% endblock %}

{% block css %}
<!-- CUSTOM STYLES -->
<link rel="stylesheet" href="{% static 'accounts/css/style.css' %}">
{% endblock %}

{% block content %}
<!-- VIEW PROFILE SECTION -->
<div class="container my-20" data-aos="fade-up">
    <h1 class="mb-20">Profile</h1>
    <p class="field"><span class="field-text">Username:</span>{{ user.username }}</p>
    <p class="field"><span class="field-text">First name:</span>{{ user.first_name }}</p>
    <p class="field"><span class="field-text">Surname:</span>{{ user.last_name }}</p>
    <p class="field"><span class="field-text">Email:</span>{{ user.email }}</p>
    <a class="btn-standard content-btn my-20" href="{% url 'accounts:edit_profile' %}">Edit profile</a>
</div>
{% endblock %}

apps/accounts/templates/accounts/reset_password.html
{% extends "base/html/base.html" %}

{% load static %}

{% block title %}Reset password - Project Avalon{% endblock %}

{% block content %}
<!-- RESET PASSWORD SECTION -->
<div class="form-page">
    <div class="form sign-up fade-in-top">
        <h2 class="heading">Reset password</h2>
        <!-- FORM -->
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

{% block javascript %}
<script>
    // Locate and move default error message positions
    $("li").each(function(index) {
        var errorText = $(this).text();
        if (errorText == "Enter a valid email address.") {
            $(this).parent().remove();
            $("#id_email").after("<p class='error-text fade-in'>" + errorText + "</p>");
            $("#id_email").delay(200).queue(function() {
                $(this).addClass('red-border');
            });
            $("#id_email").focus(function() {
                $("#id_email").removeClass('red-border');
            });
        }
    });
</script>
{% endblock %}

apps/accounts/templates/accounts/reset_password_complete.html
{% extends "base/html/base.html" %}

{% load static %}

{% block title %}Password reset complete - Project Avalon{% endblock %}

{% block content %}
<!-- POST-PASSWORD RESET SECTION -->
<div class="container my-20">
    <!-- MESSAGE -->
    <h1 class="mb-20">Password reset complete</h1>
    <p>
        Your password has been set. You may go ahead and log in now.
        <a class="btn-standard content-btn my-20" href="{% url 'accounts:login' %}">Log in</a>
    </p>

</div>
{% endblock %}

apps/accounts/templates/accounts/reset_password_done.html
{% extends "base/html/base.html" %}

{% load static %}

{% block title %}Password reset sent - Project Avalon{% endblock %}

{% block content %}
<!-- POST-PASSWORD SENT SECTION -->
<div class="container my-20">
    <!-- MESSAGE -->
    <p>
        Password reset sent.<br>
        We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.

        If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.
    </p>
    <a href="{% url 'main:home' %}">Return to home</a>
</div>
{% endblock %}

apps/accounts/templates/accounts/signup.html
{% extends "base/html/base.html" %}
<!-- Use extend instead of include since we need the entire app, not just the template. -->

{% load static %}

{% block title %}Sign up - Project Avalon{% endblock %}

{% block content %}
<!-- FORM ERROR MESSAGES -->
{% if form.non_field_errors %}
<div class="page-message form-error slide-in-top" role="alert">
    {% for error in form.non_field_errors %}
    <p class="container">{{ error }}</p>
    {% endfor %}
</div>
{% endif %}

<!-- BACKEND MESSAGES -->
{% if messages %}
<div class="page-message form-error slide-in-top" role="alert">
    {% for message in messages %}
    <p class="container">{{ message }}</p>
    {% endfor %}
</div>
{% endif %}

<!-- SIGN UP SECTION -->
<div class="form-page">
    <div class="form sign-up fade-in-top">
        <h2 class="heading">Sign up</h2>
        <!-- FORM -->
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Sign up</button>
            <a class="form-link" href="{% url 'accounts:login' %}">Already have an account? Log in</a>
        </form>
    </div>
</div>
{% endblock %}


{% block javascript %}
<script>
    // Locate and move default error message positions
    $("li").each(function(index) {
        var errorText = $(this).text();

        if (errorText == "Username already exists.") {
            $(this).parent().remove();
            $("#id_username").after("<p class='error-text fade-in'>" + errorText + "</p>");
        } else if (errorText == "Email already exists." || errorText == "Enter a valid email address.") {
            $(this).parent().remove();
            $("#id_email").after("<p class='error-text'>" + errorText + "</p>");
        } else if (errorText == "Passwords don't match.") {
            $(this).parent().remove();
            $("#id_password2").after("<p class='error-text'>" + errorText + "</p>");
        } else if (errorText == "Incorrect registration key.") {
            $(this).parent().remove();
            $("#id_regkey").after("<p class='error-text'>" + errorText + "</p>");
        }
    });

    {% for username-error in form.username.errors %}
        // If error then show red border over field
        $("#id_username").delay(300).queue(function() {
            $(this).addClass('red-border');
        });
        $("#id_username").focus(function() {
            $("#id_username").removeClass('red-border');
        });
    {% endfor %}

    {% for username-error in form.email.errors %}
        $("#id_email").delay(300).queue(function() {
            $(this).addClass('red-border');
        });
        $("#id_email").focus(function() {
            $("#id_email").removeClass('red-border');
        });
    {% endfor %}

    {% for username-error in form.password2.errors %}
        $("#id_password1, #id_password2").delay(300).queue(function() {
            $(this).addClass('red-border');
        });
        $("#id_password1, #id_password2").focus(function() {
            $("#id_password1, #id_password2").removeClass('red-border');
        });
    {% endfor %}

    {% for username-error in form.regkey.errors %}
        $("#id_regkey").delay(300).queue(function() {
            $(this).addClass('red-border');
        });
        $("#id_regkey").focus(function() {
            $("#id_regkey").removeClass('red-border');
        });
    {% endfor %}
</script>
{% endblock %}